name: sogs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10

  - cudatoolkit=11.8

  - pytorch
  - pytorch-cuda=11.8
  - torchvision

  - click
  - hydra-core
  - kornia
  - opencv
  - pandas
  - pip
  - plyfile
  - scipy
  - tqdm

  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn

    - submodules/PLAS

    - imagecodecs[all]
    - wandb
