name: sogs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - python=3.10
  - plyfile
  - pip
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - tqdm
  - kornia
  - opencv
  - scipy
  - pandas
  - click
  - hydra-core
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/PLAS
    - imagecodecs[all]
    - wandb
