dataset:
  path: ./data/FashionMNIST/
logging:
  path: ./experiments/GarmentClassifier
model:
  input_dim: 28
  name: GarmentClassifier
  output_dim: 10
training:
  batch_size: 32
  epochs: 2
  learning_rate: 0.001
