model:
  name: gaussian_splatting
logging:
  path: ./experiments/gaussian_splatting
dataset:
  path: ./data/input/meta_food_3d/croissant_sample
training:
  iterations: 15000
  source_path: ./data/input/meta_food_3d/croissant_5img
  model_path: ./data/output/gaussian_splatting/croissant_5img